import { getServerSession } from 'next-auth';
import { redirect } from 'next/navigation';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { cancelPaymentRun, createWisePaymentRun, syncWisePaymentRun } from '@/app/actions';
import { decryptBankDetail } from '@/lib/bank';

const money=(n:number)=>`£${n.toFixed(2)}`;
export default async function PaymentsPage(){
 const session=await getServerSession(authOptions); if(!session?.user) redirect('/login'); const user=session.user as any; if(!user.isAdmin&&!user.isApprover) redirect('/dashboard');
 const readyWhere:any=user.isAdmin?{status:'READY_TO_PAY'}:{status:'READY_TO_PAY',team:{OR:[{approverEmail:{equals:user.email,mode:'insensitive'}},{members:{some:{userId:user.id,role:'APPROVER'}}}]}};
 const [ready,runs]=await Promise.all([prisma.expense.findMany({where:readyWhere,include:{user:true,team:true},orderBy:{submittedAt:'asc'}}),prisma.paymentRun.findMany({where:user.isAdmin?{}:{createdById:user.id},include:{expenses:{include:{user:true,team:true}}},orderBy:{createdAt:'desc'},take:20})]);
 const payable=ready.filter(e=>e.user.bankAccountName&&e.user.bankSortCode&&e.user.bankAccountNumber); const missing=ready.filter(e=>!e.user.bankAccountName||!e.user.bankSortCode||!e.user.bankAccountNumber);
 return <div className="space-y-7"><div><p className="text-sm font-semibold text-emerald-600">Payments</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Wise payment runs.</h1><p className="mt-2 max-w-3xl text-sm text-slate-500">Approved reimbursements and advances are prepared in Wise. The app creates the Wise batch and tracks it; for UK accounts using a personal Wise API token, funding the batch still needs to be completed in Wise Business.</p></div>
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold text-slate-950">Ready to pay</h2><p className="mt-1 text-sm text-slate-500">{payable.length} payment{payable.length===1?'':'s'} · {money(payable.reduce((s,e)=>s+e.amount,0))}</p></div><form action={createWisePaymentRun}><button disabled={!payable.length} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Prepare Wise payment run</button></form></div>
   {missing.length>0&&<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">{missing.length} ready expense{missing.length===1?'':'s'} cannot be included because the requester has not saved complete bank details.</div>}
   <div className="mt-5 divide-y divide-slate-100">{payable.length===0?<p className="py-8 text-sm text-slate-500">Nothing is ready for payment.</p>:payable.map(e=><div key={e.id} className="flex flex-col gap-2 py-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-slate-900">{e.description}</p><p className="text-xs text-slate-500">{e.user.name||e.user.email} · {e.team.name} · {decryptBankDetail(e.user.bankSortCode!)} / ••••••••{decryptBankDetail(e.user.bankAccountNumber!).slice(-4)}</p></div><span className="font-semibold">{money(e.amount)}</span></div>)}</div>
  </section>
  <section><h2 className="mb-3 font-semibold text-slate-950">Recent Wise runs</h2>{runs.length===0?<div className="rounded-2xl border border-dashed border-slate-300 bg-white py-12 text-center text-sm text-slate-500">No payment runs yet.</div>:<div className="space-y-3">{runs.map(run=><article key={run.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-slate-900">{run.reference}</p><p className="mt-1 text-xs text-slate-500">{run.expenses.length} payment{run.expenses.length===1?'':'s'} · {money(run.totalAmount)} · {run.createdAt.toLocaleDateString('en-GB')}</p>{run.wiseBatchGroupId&&<p className="mt-1 text-xs text-slate-400">Wise batch: {run.wiseBatchGroupId}</p>}</div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full border border-slate-200 px-2.5 py-1 text-xs font-medium text-slate-600">{run.status}</span>{run.status!=='COMPLETED'&&run.status!=='CANCELLED'&&<form action={syncWisePaymentRun}><input type="hidden" name="runId" value={run.id}/><button className="rounded-xl bg-emerald-700 px-3 py-2 text-xs font-semibold text-white">Sync Wise status</button></form>}{run.status!=='COMPLETED'&&run.status!=='CANCELLED'&&<form action={cancelPaymentRun}><input type="hidden" name="runId" value={run.id}/><button className="rounded-xl border border-rose-200 px-3 py-2 text-xs font-semibold text-rose-700">Cancel run</button></form>}<a href={`/api/payments/export?runId=${run.id}`} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700">Export CSV</a></div></div></article>)}</div>}</section>
  <section className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><h2 className="font-semibold text-blue-950">How Wise works here</h2><ol className="mt-2 list-decimal space-y-1 pl-5 text-sm text-blue-900"><li>The app creates recipients, GBP quotes and a Wise batch.</li><li>The batch is completed so it can be funded.</li><li>For a UK Wise Business account using a personal API token, open Wise Business and fund the completed batch from the GBP balance.</li><li>Use “Sync Wise status” to bring payment states back into Proclaim Expenses.</li></ol></section>
 </div>;
}
