'use client';
import { useTransition } from 'react';
import { BarChart, Bar, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { updateBudget } from '@/app/actions';
const fmt=(n:number)=>`£${n.toFixed(2)}`;
export type TeamSummary={id:string;name:string;target:number;spent:number;canEdit:boolean};
export default function BudgetCharts({teams,barData,trendData}:{teams:TeamSummary[];barData:{name:string;Spent:number;Target:number}[];trendData:{month:string;Spend:number}[]}){
 const[,startTransition]=useTransition();
 return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{teams.map(t=>{const pct=t.target?Math.min(100,t.spent/t.target*100):0;const over=t.spent>t.target;return <div key={t.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-slate-950">{t.name}</p><p className="mt-1 text-2xl font-bold tracking-tight text-slate-950">{fmt(t.spent)}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${over?'bg-rose-100 text-rose-700':'bg-emerald-100 text-emerald-700'}`}>{over?'Over budget':'On track'}</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${over?'bg-rose-500':'bg-emerald-500'}`} style={{width:`${pct}%`}}/></div><div className="mt-3 flex items-center justify-between gap-2 text-xs text-slate-500"><span>Target</span>{t.canEdit?<input type="number" min="0" step="0.01" defaultValue={t.target} onBlur={e=>{const v=parseFloat(e.target.value);if(!Number.isNaN(v)&&v>=0)startTransition(()=>updateBudget(t.id,v));}} className="w-28 rounded-lg border border-slate-200 px-2 py-1 text-right text-xs"/>:<span>{fmt(t.target)}</span>}</div></div>})}</div><div className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="font-semibold text-slate-950">Spend vs target</p><p className="mb-4 text-xs text-slate-500">Current spend compared with each team target.</p><ResponsiveContainer width="100%" height={280}><BarChart data={barData}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0"/><XAxis dataKey="name" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}}/><Tooltip formatter={(v:any)=>fmt(v)}/><Bar dataKey="Spent" fill="#0f172a" radius={[5,5,0,0]}/><Bar dataKey="Target" fill="#cbd5e1" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="font-semibold text-slate-950">Monthly spend</p><p className="mb-4 text-xs text-slate-500">A simple view of spending over time.</p>{trendData.length===0?<p className="py-20 text-center text-sm text-slate-400">No expenses logged yet.</p>:<ResponsiveContainer width="100%" height={280}><LineChart data={trendData}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0"/><XAxis dataKey="month" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}}/><Tooltip formatter={(v:any)=>fmt(v)}/><Line type="monotone" dataKey="Spend" stroke="#0f172a" strokeWidth={3} dot={{r:3}}/></LineChart></ResponsiveContainer>}</div></div></div>
}
