'use client';
import { useState, useTransition } from 'react';
import { markExpensePurchased } from '@/app/actions';
import { Upload, Trash2 } from 'lucide-react';
import DateField from './DateField';

export default function MarkPurchasedForm({ expenseId }: { expenseId:string }) {
 const [open,setOpen]=useState(false); const [receiptUrl,setReceiptUrl]=useState<string|null>(null); const [preview,setPreview]=useState<string|null>(null); const [type,setType]=useState(''); const [name,setName]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [pending,startTransition]=useTransition();
 async function upload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setError('');if(file.size>4*1024*1024){setError('This file is too large. Please choose a receipt smaller than 4MB.');e.target.value='';return;}setBusy(true);try{const fd=new FormData();fd.append('file',file);const r=await fetch('/api/receipts/upload',{method:'POST',body:fd});const raw=await r.text();let d:any={};try{d=raw?JSON.parse(raw):{}}catch{throw new Error(r.status===413?'This file is too large. Please choose a receipt smaller than 4MB.':'We could not upload this receipt. Please try again.')}if(!r.ok)throw new Error(d.error||(r.status===413?'This file is too large. Please choose a receipt smaller than 4MB.':'We could not upload this receipt. Please try again.'));setReceiptUrl(d.url);setPreview(d.previewUrl||d.url);setType(d.contentType||file.type);setName(file.name)}catch(err:any){setError(err.message||'We could not upload this receipt. Please try again.')}finally{setBusy(false)}}
 if(!open)return <button onClick={()=>setOpen(true)} className="rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-semibold text-white">I've bought it</button>;
 return <div className="mt-3 rounded-2xl border border-blue-200 bg-blue-50/50 p-4"><p className="text-sm font-semibold text-slate-900">Finish the purchase</p><p className="mt-1 text-xs text-slate-500">Upload the receipt and enter the actual amount so the expense can move to payment or reconcile the advance.</p><form action={fd=>startTransition(async()=>{setError('');try{await markExpensePurchased(fd);setOpen(false)}catch(e:any){setError(e?.message||'Could not update the expense.')}})} className="mt-4 space-y-3"><input type="hidden" name="expenseId" value={expenseId}/><input type="hidden" name="receiptUrl" value={receiptUrl||''}/><div><label className="block text-xs font-semibold text-slate-600">Actual amount on receipt</label><input name="actualAmount" type="number" step="0.01" min="0.01" onWheel={(e) => e.currentTarget.blur()} required placeholder="0.00" className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm [appearance:textfield] [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:appearance-none" /></div><div><label className="block text-xs font-semibold text-slate-600">Purchase date</label><div className="mt-1"><DateField name="purchaseDate" defaultValue={new Date().toISOString().slice(0,10)} required/></div></div>{!receiptUrl?<label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border-2 border-dashed border-slate-300 bg-white py-5 text-sm text-slate-500"><Upload size={16}/>{busy?'Uploading…':'Upload receipt'}<input type="file" accept="image/*,application/pdf" className="hidden" onChange={upload} disabled={busy}/></label>:<div className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-3">{type==='application/pdf'?<div className="grid h-14 w-14 place-items-center rounded bg-slate-100 text-xs font-bold">PDF</div>:<img src={preview||receiptUrl} className="h-14 w-14 rounded object-cover" alt="Receipt preview"/>}<div className="min-w-0 flex-1"><p className="truncate text-sm">{name}</p><button type="button" onClick={()=>{setReceiptUrl(null);setPreview(null);setType('');setName('')}} className="mt-1 flex items-center gap-1 text-xs text-rose-600"><Trash2 size={12}/> Remove</button></div></div>}{error&&<p className="text-sm text-rose-600">{error}</p>}<div className="flex gap-2"><button disabled={pending||busy} className="rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-semibold text-white disabled:opacity-60">{pending?'Saving…':'Confirm purchase'}</button><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-semibold text-slate-700">Cancel</button></div></form></div>;
}
