'use client';

import { signIn } from 'next-auth/react';
import { ArrowRight, CheckCircle2, Wallet } from 'lucide-react';

export default function LoginPage() {
  return <main className="min-h-screen bg-slate-950 text-white lg:grid lg:grid-cols-2">
    <section className="relative hidden overflow-hidden lg:flex lg:min-h-screen lg:flex-col lg:justify-between lg:p-12"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(16,185,129,.22),transparent_35%),radial-gradient(circle_at_80%_80%,rgba(59,130,246,.18),transparent_35%)]"/><div className="relative flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-white text-slate-950"><Wallet size={21}/></div><div><p className="font-semibold">Proclaim</p><p className="text-xs text-slate-400">Expenses & budgeting</p></div></div><div className="relative max-w-xl"><h1 className="text-5xl font-bold leading-tight tracking-tight xl:text-6xl">Proclaim expenses</h1><p className="mt-6 max-w-lg text-xl leading-8 text-slate-300">Expenses, made easy. Stewarding God&rsquo;s finances <span className="font-cursive text-3xl font-bold text-emerald-300">together</span></p><div className="mt-8 space-y-3 text-sm text-slate-200"><p className="flex items-center gap-2"><CheckCircle2 size={17} className="text-emerald-300"/> Clear approval routing</p><p className="flex items-center gap-2"><CheckCircle2 size={17} className="text-emerald-300"/> Simple expense tracking</p><p className="flex items-center gap-2"><CheckCircle2 size={17} className="text-emerald-300"/> Receipts and reports in one place</p></div></div><p className="relative text-xs text-slate-500">Proclaim Expenses</p></section>
    <section className="flex min-h-screen items-center justify-center bg-slate-50 p-6 text-slate-950 sm:p-10"><div className="w-full max-w-md"><div className="mb-10 flex items-center gap-3 lg:hidden"><div className="grid h-10 w-10 place-items-center rounded-xl bg-slate-950 text-white"><Wallet size={19}/></div><div><p className="font-semibold">Proclaim expenses</p><p className="text-xs text-slate-500">Expenses, made easy. Stewarding God&rsquo;s finances <span className="font-cursive text-base font-bold text-emerald-600">together</span></p></div></div><div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-xl shadow-slate-200/60 sm:p-9"><p className="text-sm font-semibold text-emerald-700">Welcome back</p><h2 className="mt-2 text-3xl font-bold tracking-tight">Sign in to Proclaim</h2><p className="mt-3 text-sm leading-6 text-slate-500">Manage requests, approvals and expenses from one place.</p><button onClick={() => signIn('google', { callbackUrl: '/' })} className="mt-8 flex w-full items-center justify-between rounded-xl bg-slate-950 px-4 py-3.5 text-sm font-semibold text-white transition hover:bg-slate-800 active:scale-[.99]"><span>Continue with Google</span><ArrowRight size={17}/></button></div></div></section>
  </main>;
}
